from github import Github, Auth
import subprocess
import os
import anthropic
from dotenv import load_dotenv
from playwright.sync_api import sync_playwright
from datetime import datetime


# Load the API key from .env file
load_dotenv()

# Create the Anthropic client - this is what talks to Claude
client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

# GitHub client
auth = Auth.Token(os.getenv("GITHUB_TOKEN"))
github_client = Github(auth=auth)
repo = github_client.get_repo(os.getenv("GITHUB_REPO"))

def get_page_html(url):
    """
    Opens the actual webpage using Playwright
    and returns its real HTML content
    """
    print(f"🌐 Opening page to inspect real HTML: {url}")

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        page = browser.new_page()
        page.goto(url)

        # Wait for the page to fully load
        page.wait_for_load_state("networkidle")

        # Grab the actual HTML of the page
        html = page.content()

        browser.close()
        return html


def get_claude_fix(test_file_path, error_message, page_url):
    """
    Takes a broken test file and its error message,
    end both to Claude, gets back a fixed version
    """

    # Read the broken test file
    with open(test_file_path, "r") as f:
        brokentest_code = f.read()

    # Get the Real HTML from the actual webpage
    real_html = get_page_html(page_url)    

    # Build the prompt - this is what we send to Claude
    prompt = f""" 
    You are a test automation expert
    A playwright/pytest test is failing

    Here is the broken test code:
```python
    {brokentest_code}
```

    Here is the error message:
    {error_message}

    Here is the REAL HTML of the page the test is running against:
```html
    {real_html}
```    

    Instructions :
    - Look at the real HTNL above
    - Find the correct selectors that actually exists in the HTML
    - Fix the broken test code using ONLY selectors that exist in the real HTML
    - Do not guess - use what you can see in the HTML
    - Return ONLY the fixed python code, no explanations.
    """

    print("🤖 Sending real HTML to Claude for analysis...")

    # Send to claude and get response
    message = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=1024,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    # Extract the fixed code from Claude's response
    fixed_code = message.content[0].text

    #Clean up the response - Claude sometimes wraps code in ```python blocks`
    if "```python" in fixed_code:
        fixed_code = fixed_code.split("```python")[1].split("```")[0].strip()

    return fixed_code    


def save_healed_test(test_file_path, fixed_code):
    """
    Save the fixed code back to the same test file,
    overwritting the broken version 
    """

    with open(test_file_path, "w") as f:
        f.write(fixed_code)

    print(f"✓ Healed test saved to {test_file_path}")

def create_healing_pr(test_file_path, error_message, page_url, test_name):
    """
    1. Gets Claude's fix
    2. Creates a new branch
    3. Pushes fixed test to that branch
    4. Opens a Pull Request for human review
    """

    # Step 1 — Get Claude's fix
    fixed_code = get_claude_fix(test_file_path, error_message, page_url)

    # Step 2 — Create branch name with timestamp
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    branch_name = f"fix/heal-{test_name}-{timestamp}"

    print(f"🌿 Creating branch: {branch_name}")

    main_branch = repo.get_branch("main")
    main_sha = main_branch.commit.sha

    repo.create_git_ref(
        ref=f"refs/heads/{branch_name}",
        sha=main_sha
    )
    print(f"✓ Branch created: {branch_name}")

    print(f"📤 Pushing fix to branch...")
    github_file = repo.get_contents(test_file_path, ref="main")
    repo.update_file(
        path=test_file_path,
        message=f"🤖 Auto-heal: fix locator in {test_name}",
        content=fixed_code,
        sha=github_file.sha,
        branch=branch_name
    )
    print(f"✓ Fix pushed to branch")

    print(f"📬 Opening Pull Request...")

    # Build PR body separately to avoid backtick clash
    short_error = error_message[-500:]
    pr_body = (
        "## 🤖 Auto-generated by Self Healing Test Framework\n\n"
        f"**Test that failed:** `{test_name}`\n"
        f"**File:** `{test_file_path}`\n"
        f"**Time:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        "---\n\n"
        "## What failed\n"
        "```\n"
        f"{short_error}\n"
        "```\n\n"
        "## What Claude fixed\n"
        "Claude inspected the real HTML of the page and identified "
        "the correct selector to replace the broken one.\n\n"
        "## How to review\n"
        "1. Click **Files changed** tab above\n"
        "2. Verify the selector change looks correct\n"
        "3. Click **Merge pull request** if happy ✅\n\n"
        "---\n"
        "*This PR was automatically created by the self healing test framework*"
    )

    pr = repo.create_pull(
        title=f"🤖 Auto-heal: Fix failing test {test_name}",
        body=pr_body,
        head=branch_name,
        base="main"
    )

    print(f"✅ Pull Request opened!")
    print(f"🔗 {pr.html_url}")
    return pr