from playwright.sync_api import sync_playwright
from dotenv import load_dotenv
from github import Github, Auth
from datetime import datetime
import os

load_dotenv()

auth = Auth.Token(os.getenv("GITHUB_TOKEN"))
github_client = Github(auth=auth)
repo = github_client.get_repo(os.getenv("GITHUB_REPO"))

ALWAYS_IGNORE = ["toggle-navigation", "menu-toggle"]


def check_page_contract(url, contract, contract_name="login_page"):
    """
    1. Check required elements exist  → if missing = product bug
    2. Check for new elements         → create PR to add to contract
    """
    print(f"\n🔍 Checking page contract for {url}")

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.set_default_timeout(60000)
        page.goto(url, wait_until="domcontentloaded")
        page.wait_for_timeout(2000)

        # CHECK 1: Required elements still exist?
        for selector in contract.get("required_elements", []):
            count = page.locator(selector).count()
            if count == 0:
                browser.close()
                reason = f"Required element missing: {selector}"
                print(f"❌ {reason}")
                return "product_bug", reason, []
            print(f"✅ Element found: {selector}")

        # CHECK 2: Any new elements appeared?
        current_elements = set()

        inputs = page.locator("input[id]").all()
        for el in inputs:
            el_id = el.get_attribute("id")
            if el_id:
                current_elements.add(f"#{el_id}")

        buttons = page.locator("button[id]").all()
        for el in buttons:
            el_id = el.get_attribute("id")
            if el_id:
                current_elements.add(f"#{el_id}")

        links = page.locator("a[id]").all()
        for el in links:
            el_id = el.get_attribute("id")
            if el_id:
                current_elements.add(f"#{el_id}")

        browser.close()

        contract_elements = set(contract.get("required_elements", []))
        new_elements = current_elements - contract_elements

        # Remove always-ignored elements
        new_elements = {
            el for el in new_elements
            if not any(ignore in el.lower() for ignore in ALWAYS_IGNORE)
        }

        if new_elements:
            reason = (
                f"New elements detected: {', '.join(new_elements)}."
            )
            print(f"🟡 {reason}")
            return "change_detected", reason, list(new_elements)

    print(f"✅ Page contract valid!")
    return "valid", "All checks passed", []


def create_contract_pr(contract_name, new_elements):
    """
    Creates a PR to add new elements to contracts.py
    Human reviews before it gets merged
    """
    print(f"📬 Creating PR to update contract...")

    # Read current contracts.py from GitHub
    github_file = repo.get_contents("healer/contracts.py", ref="main")
    current_content = github_file.decoded_content.decode("utf-8")

    # Add new elements to the contract
    updated_content = current_content
    for element in new_elements:
        if element not in updated_content:
            old = '"required_elements": ['
            new = f'"required_elements": [\n            "{element}",'
            updated_content = updated_content.replace(old, new, 1)

    # Create new branch
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    branch_name = f"fix/contract-update-{contract_name}-{timestamp}"

    main_branch = repo.get_branch("main")
    repo.create_git_ref(
        ref=f"refs/heads/{branch_name}",
        sha=main_branch.commit.sha
    )
    print(f"✓ Branch created: {branch_name}")

    # Push updated contracts.py to branch
    repo.update_file(
        path="healer/contracts.py",
        message=f"🤖 Auto-detected new elements for {contract_name}",
        content=updated_content,
        sha=github_file.sha,
        branch=branch_name
    )
    print(f"✓ Contract update pushed to branch")

    # Create PR
    pr_body = (
        f"## 🤖 Auto-detected Contract Update\n\n"
        f"**Contract:** `{contract_name}`\n"
        f"**Time:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        f"---\n\n"
        f"## New elements detected\n"
        f"{chr(10).join(f'- `{el}`' for el in new_elements)}\n\n"
        f"## Action required\n"
        f"1. Review the new elements above\n"
        f"2. Confirm they were intentionally added to the page\n"
        f"3. Check if there is a ticket for this change\n"
        f"4. Merge if correct ✅ or close if not needed ❌\n\n"
        f"---\n"
        f"*Auto-generated by self healing test framework*"
    )

    pr = repo.create_pull(
        title=f"🤖 Contract update: new elements on {contract_name}",
        body=pr_body,
        head=branch_name,
        base="main"
    )

    print(f"✅ Contract PR opened!")
    print(f"🔗 {pr.html_url}")
    return pr