import os
from github import Github, Auth
from dotenv import load_dotenv
from datetime import datetime

load_dotenv()

# New authentication method (fixes deprecation warning)
auth = Auth.Token(os.getenv("GITHUB_TOKEN"))
github_client = Github(auth=auth)
repo = github_client.get_repo(os.getenv("GITHUB_REPO"))


def create_sim(title, body, label, screenshot_path=None):
    """
    Creates a GitHub Issue automatically when a bug is found

    title            = Issue Title
    body             = Issue description with full details
    label            = "api-down", "product-bug", or "healing-failed"
    screenshot_path  = optionaal path to screenshot file
    """

    #Create the issue body woth timestamp

    full_body = f"""
## 🤖 Auto-generated by Self Healing Test Framework

**Timestamo:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

{body}

---
*This issue was automatically created by the self healing test framework*
    """

    # Make sure the label exists in the GitHub, create if not
    ensure_label(label)

    # Create the GutHub issue
    issue = repo.create_issue(title=f"[AUTO] {title}",
                              body=full_body,
                              labels=[label]
                            )
    
    print(f"🎫 SIM created → GitHub Issue #{issue.number}: {issue.title}")
    print(f"🔗 {issue.html_url}")
    
    return issue


def ensure_label(label_name):
    """
    Creates the label in GutHub if it doesn't exist yet
    """

    # Define our labels with colors
    label_config = {
        "api_down" : ("d73a4a", "API is returning non-200 status"),
        "product-bug": ("e4e669", "Screenshot mismatch detected"),
        "healing-failed": ("0075ca", "Self healing could not fix the test"),
        "healed": ("0e8a16", "Test was successfully self healed")
    }

    # Get existing labels in the repo
    existing = [l.name for l in repo.get_labels()]

    if label_name not in existing:
        color, description = label_config.get(label_name, ("ffffff", ""))
        repo.create_label(
            name=label_name,
            color=color,
            description=description
        )

        print(f"✓ Created GitHub label: {label_name}")


